### ISSUE TITLE
Sidebar location

### ISSUE THREAD

**Issue by MoonshineSG** [OctoPrint/OctoPrint-AutomaticShutdown#1]
can this be moved ABOVE the Files list ? It would be much more visible...

**Comment by nicanor-romero** [comment]
Hi @MoonshineSG ! I'm afraid that is not possible. As stated here http://docs.octoprint.org/en/master/plugins/mixins.html#templateplugin plugins can only add elements beneath the existing sections.

**Comment by Salandora** [comment]
Hi @MoonshineSG
you could try this: http://docs.octoprint.org/en/master/configuration/config_yaml.html#appearance

As I understand it right you can simply define the order the items appear.

**Comment by MoonshineSG** [comment]
Never mind. The plugin doesn't really work so I removed it.

**Comment by nicanor-romero** [comment]
@MoonshineSG Do you mind explaining why it isn't working for you?

**Comment by MoonshineSG** [comment]
Apologies!!! It was entirely my fault. All I had to do was RTFM.  I am not using "systemShutdownCommand". This is not a plugin issue.
