### ISSUE TITLE
Does not shut down

### ISSUE THREAD

**Issue by hoegge** [OctoPrint/OctoPrint-AutomaticShutdown#15]
Hi

I just installed the plugin but it does not shut down. I have checked the shutdown command is filled (and works). I have tried with different time out values - not clear what would abort timeout since nothing happens after a print.

**Comment by kantlivelong** [comment]
Need more info.

- OS?
- OctoPrint Version?
- Shutdown command defined in OctoPrint?
- Include logs with the issue occurring

**Comment by hoegge** [comment]
Hi, Sorry for delay

I updated to the latest version released last week or the week before and then it works. So cannot attach log with problem.

OctoPrint version : 1.3.6
OctoPi version    : 0.14.0
Linux octopi 4.9.28-v7+ #998 SMP Mon May 15 16:55:39 BST 2017 armv7l GNU/Linux
Command: sudo shutdown -h now
