### ISSUE TITLE
No script executed after countdown

### ISSUE THREAD

**Issue by MasterPIC** [OctoPrint/OctoPrint-AutomaticShutdown#18]
Hi,
I just installed the plugin.
At the end of the countdown it doesn't shutdown the printer as if it doesn't execute the script.
The shutdown system command works flawlessly. I'm using a script that calls another script and a "sudo shutdown" command.
What is wrong?

**Comment by kantlivelong** [comment]
Can you provide logs with the issue occurring?

**Comment by MasterPIC** [comment]
I can see just the following expected log in octoprint.log:

> 2018-06-18 18:22:26,890 - octoprint.plugins.automaticshutdown - INFO - Shutting down system with command: sh ~/.octoprint/scripts/OFF.sh

**Comment by MasterPIC** [comment]
I've no octoprint.plugins.automaticshutdown logs.
Should I restart Octoprint after adding (debug level?) octoprint.plugins.automaticshutdown logs?

**Comment by MasterPIC** [comment]
OK,

I set
`sh /home/pi/.octoprint/scripts/OFF.sh`

in place of

`sh ~/.octoprint/scripts/OFF.sh`

and it seems working as expected.
I'm going to restart Octoprint to check again...

**Comment by MasterPIC** [comment]
OK,
it works as expected.
