### ISSUE TITLE
Cannot access screen to add tp-link ip address

### ISSUE THREAD

**Issue by chuckwain** [OctoPrint/OctoPrint-AutomaticShutdown#19]
When I go to the setting screen for this plugin all I get is this screen:

![screen shot 2018-06-19 at 6 38 06 pm](https://user-images.githubusercontent.com/8485826/41631121-1b28864c-73f0-11e8-989b-f1c667147709.png)It 

The screen only shows an abort timer setting, no way to set the ip address.  I have looked over the instructions several times, but cannot get by this.   Any ideas?
Thanks

**Comment by kantlivelong** [comment]
This plugin doesn't include any support for tplink devices. You may be thinking of another plugin.

**Comment by chuckwain** [comment]
Yes my mistake!
Thanks
Chuck


Sent from Mail for Windows 10
