### ISSUE TITLE
disturbed touchui when installing automatic shutdown

### ISSUE THREAD

**Issue by FischFuss** [OctoPrint/OctoPrint-AutomaticShutdown#25]
Octopi Version 0.17.0, running on Raspberry Pi 3 Model B Plus Rev 1.3
Octoprint Version 1.3.12

After installing automatic shutdown, the display of my 3.5 '' TFT touchscreen that uses touchui is disturbed.
The display is still working, but the controls are no longer available and I can no longer control the printer via the touchui.
If I then uninstall automatic shutdown again, everything works as usual.
Apparently there is a conflict between Touchui and automatic shutdown.
The error only occurred when upgrading Octoprint to version 1.3.12, before that both worked perfectly.

thanks for your help

EDIT: After a few minutes the screen crashes and the following message appears: "Touchui startup failure, tap to retry"

**Comment by kantlivelong** [comment]
This should probably be logged with TouchUI. This plugin only supports the base UI.
