### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by hongkongkiwi** [OctoPrint/OctoPrint-AutomaticShutdown#3]
Great plugin thanks!

If possible I would like to request the following features:
- Setting to default automatic shutdown to true
- Ability to set the action that's performed (instead of shutdown), as I want to have a different system shutdown to just turning off the printer

**Comment by malebuffy** [comment]
I also want a custom command since I am using gpio pin 23 (pin 4 from witingPI) to power on/off my printer.

**Comment by totalitarian** [comment]
custom command would be great

**Comment by kantlivelong** [comment]
@hongkongkiwi @malebuffy: Perhaps this plugin might interest you http://plugins.octoprint.org/plugins/psucontrol


As for the default value of the checkbox, would it make sense to have an option to remember the state?

**Comment by malebuffy** [comment]
thanks for the link! yes would make sense!

**Comment by kantlivelong** [comment]
Added option to remember last value of checkbox.

Will be in upcoming release.
