### ISSUE TITLE
Change timeout, so camera is given more time to make a picture

### ISSUE THREAD

**Issue by fraternl** [OctoPrint/OctoPrint-AutomaticShutdown#4]
I'm using your plugin for automatic shutdown as I'm using a plugin that will mail me a picture of the finished print.
The camera on my Raspberry Pi is unable to make a decent picture without enough lighting.
The lighting of the printer is hardwired to the power supply of the printer.

When the printer shuts down after printing it will not wait long enough for the picture to be taken.
I'm therefore getting a dark picture...

I've changed in **init**.py

self._timeout_value = 10

into

self._timeout_value = 30

I think this will do the trick....
Will it?

**Comment by nicanor-romero** [comment]
Hi @fraternl . Yes, that should do the trick :)

**Comment by Helisinus** [comment]
Where can i found this init.py ?
i need to change this value too

**Comment by fraternl** [comment]
The file name is not init.py
Github is doing that

`find -name __init__.py | grep automaticshutdown
`

**Comment by kantlivelong** [comment]
Would anyone be willing to test out a new devel version that fixes(hopefully) this? I currently do not have a camera.

**Comment by kantlivelong** [comment]
Fixed in upcoming release.
