### ISSUE TITLE
Access to checkbox when not logged in?

### ISSUE THREAD

**Issue by chunkysteveo** [OctoPrint/OctoPrint-AutomaticShutdown#5]
When I access my Octoprint server as a standard user (not logged in) the tickbox to shut down the system is visible. Will this allow anyone (who has access) to shut down your Raspberry Pi?

**Comment by markwal** [comment]
Which checkbox (where do you see it)?  In my set up, that command is only on the System menu which only appears when I'm logged in.

**Comment by chunkysteveo** [comment]
When I access the web frontend of OctoPrint as a non logged in user I see the "Shutdown after print finishes" checkbox on the left hand nav column under the Files box (as per the screenshot of the plugin readme). I thought I wouldn't be able to see that unless I was logged in? Have not tested it, but was able to check/uncheck it as a non-logged in user.

**Comment by markwal** [comment]
Sorry about that.  I had lost context when going through the notifications. 

Looking at the code, it looks like it needs to implement the is_api_adminonly method: http://docs.octoprint.org/en/master/plugins/mixins.html?highlight=admin#octoprint.plugin.SimpleApiPlugin.is_api_adminonly

Though the js then needs to fail gracefully when it can't get the current value from the api and recover after login.

Is @nicanor-romero still maintaining this plugin?

**Comment by nicanor-romero** [comment]
Hi guys. I'll try to fix this over the weekend ;)

**Comment by chunkysteveo** [comment]
Ahh great stuff, quickly spotted guys!

**Comment by kantlivelong** [comment]
Fixed in upcoming release.
