### ISSUE TITLE
Check box flag disappear 

### ISSUE THREAD

**Issue by alebrescia** [OctoPrint/OctoPrint-AutomaticShutdown#6]
if i put the flag to automatic shutdown and then close the browser or the tab, when i try reconnect to the octoprint web interface the flag on the automatic shutdown checkbox was disappear... 
i think that's only a "visual" problem because the auto shutdown works fine.....
sry for my bad english.... i hope you can understand..... ^_^

**Comment by Helisinus** [comment]
Hi, same issue here. is it possibe to "fix" the visability of the checkbox?

**Comment by totalitarian** [comment]
Same issue too. Please fix this :)

**Comment by foosel** [comment]
@nicanor-romero do you still maintain this plugin or should it be considered abandoned? If so I'll look if I can find someone who can adopt it.

**Comment by nicanor-romero** [comment]
@foosel Hi Gina! I'm afraid I don't have time to maintain this plugin at the moment. So feel free to find someone who can :)

**Comment by foosel** [comment]
@nicanor-romero ok, will do :) I assume that also applies to any other plugins by you? 

Hope all is well on your end!

**Comment by nicanor-romero** [comment]
@foosel Yes, the other plugins as well.

**Comment by kantlivelong** [comment]
Would anyone be willing to test out a fix from my repo?

https://github.com/kantlivelong/OctoPrint-AutomaticShutdown

**Comment by totalitarian** [comment]
@kantlivelong I will, how to install it? Just download the files and copy them onto the SDcard?

**Comment by kantlivelong** [comment]
@totalitarian

Assuming you are running Octoprint on linux:

1. Uninstall the plugin from plugin manager.
2. From the URL provided download and copy octoprint_automaticshutdown to the octoprint local plugins directory (in my case /home/pi/.octoprint/plugins/)
3. Rename the copied directory octoprint_automaticshutdown to automaticshutdown.
4. Restart Octoprint

**Comment by foosel** [comment]
Uninstalling and just copy-pasting the URL of the zip download:

![image](https://cloud.githubusercontent.com/assets/83657/22247892/63195d7e-e23c-11e6-94b0-5c840f65e886.png)

into Plugin Manager 

![image](https://cloud.githubusercontent.com/assets/83657/22247870/4b1d1a9e-e23c-11e6-90ef-6f942ccb5c68.png)

should also work.

**Comment by totalitarian** [comment]
Thanks, it doesn't seem to work. If I check the box, then reload the page, the box is no longer checked

**Comment by kantlivelong** [comment]
Whoops. I solved syncing of the checkbox state across connected clients but neglected to send the state when first connecting. I was able to test it on my side and it appears to be okay now.

Could you try again with the same URL?

**Comment by totalitarian** [comment]
@kantlivelong Perfect! That you so much for fixing this 👍
